// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: topics.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (id, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, created_by
`

type CreateTopicParams struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedBy int32     `json:"created_by"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRowContext(ctx, createTopic, arg.ID, arg.Name, arg.CreatedBy)
	var i Topic
	err := row.Scan(&i.ID, &i.Name, &i.CreatedBy)
	return i, err
}

const getTopicByName = `-- name: GetTopicByName :one
SELECT id, name, created_by
FROM topics
WHERE name = $1
`

func (q *Queries) GetTopicByName(ctx context.Context, name string) (Topic, error) {
	row := q.db.QueryRowContext(ctx, getTopicByName, name)
	var i Topic
	err := row.Scan(&i.ID, &i.Name, &i.CreatedBy)
	return i, err
}
