// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: topics.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTopic = `-- name: CreateTopic :one
INSERT INTO topics (id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateTopicParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) CreateTopic(ctx context.Context, arg CreateTopicParams) (Topic, error) {
	row := q.db.QueryRowContext(ctx, createTopic, arg.ID, arg.Name)
	var i Topic
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteTopicByID = `-- name: DeleteTopicByID :one
DELETE FROM topics WHERE id = $1 RETURNING id, name
`

func (q *Queries) DeleteTopicByID(ctx context.Context, id uuid.UUID) (Topic, error) {
	row := q.db.QueryRowContext(ctx, deleteTopicByID, id)
	var i Topic
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getTopicByName = `-- name: GetTopicByName :one
SELECT id, name
FROM topics
WHERE name = $1
`

func (q *Queries) GetTopicByName(ctx context.Context, name string) (Topic, error) {
	row := q.db.QueryRowContext(ctx, getTopicByName, name)
	var i Topic
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
