// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_topic.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserTopic = `-- name: CreateUserTopic :one
INSERT INTO user_topics (
        id,
        created_at,
        updated_at,
        user_id,
        topic_id
    )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, topic_id
`

type CreateUserTopicParams struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UserID    int32     `json:"user_id"`
	TopicID   uuid.UUID `json:"topic_id"`
}

func (q *Queries) CreateUserTopic(ctx context.Context, arg CreateUserTopicParams) (UserTopic, error) {
	row := q.db.QueryRowContext(ctx, createUserTopic,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.TopicID,
	)
	var i UserTopic
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.TopicID,
	)
	return i, err
}
